---
title: "HM_Unit_5_fin"
author: "Solange GarciadeAlford"
date: "September 29, 2018"
output: 
  html_document:
   keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown = Unit 5

## Question #1

```{r }

myt = read.table('C:/Users/solan/HW_Unit_5/yob2016.txt',  sep = ";", fill=TRUE)

df <- data.frame(myt[,1:3])

df$Year<- 2016

names(df)[1] <- "Name"
names(df)[2] <- "Sex"
names(df)[3] <- "Number2016"
names(df)[4] <- "Year2016"

names(df)

summary(df)
structure(df)
str(df)

##sort the file

library(dplyr)

df <- arrange(df, Name)


## find name with triple ys and display it
a <- grep("yyy$", df$Name, value=TRUE)
a
which(df$Name == a)

## remove 'a'

y2016 <- df[!(df$Name %in% a), ]

str(y2016)

```

## Question #2


```{r }

myt = read.table('C:/Users/solan/HW_Unit_5/yob2015.txt',  sep = ",", fill=TRUE)

y2015<- data.frame(myt[,1:3])

y2015$Year<- 2015

names(y2015)[1] <- "Name"
names(y2015)[2] <- "Sex"
names(y2015)[3] <- "Number2015"
names(y2015)[4] <- "Year2015"
names(y2015)


summary(y2015)
str(y2015)

head(y2015, 10)


##sort the file

y2015 <- arrange(y2015, Name)

## display the last 10 rows

tail(y2015, 10)

##there are very few people named with the last 10 names in the file, for the sorted by name version of the file. The number of people for the last 10 names does not go higher than 30.

## The unsorted version of the file, the last 10 records are all girls.



## Part c or Q2 - Merge the files


final <- merge(y2015, y2016, by = "Name")
head(final,10)
tail(final,10)


## sort final by Name and Add colum

final <- arrange(final, Name)

final$Total <- 5
  
final$Total <- final$Number2015 + final$Number2016


names(final)


final <- arrange(final, Total)
head(final,10)

##The 10 top most popular names are:
tail(final,10)



##Omit boys
FinalGirls <- final[ !(final$Sex.x %in% "M"), ]



##Th 10 top most popular girl names are:
tail(FinalGirls,10)

FinalGirls <- data.frame(FinalGirls$Name, FinalGirls$Total)

Top10 <- tail(FinalGirls,10)

write.csv(Top10, file = "Top10GirlNames.csv")

```

